FROM debian:buster-slim

# RUN chown -R 1000:1000 /opt/satosa/ /src/satosa/
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y --no-install-recommends install \
        python3 \
        python3-pip \
        xmlsec1 \
        python3-setuptools \
    && apt-get -y autoremove \
    && apt-get -y clean

WORKDIR /

COPY requirements.txt /
COPY tests/test_requirements.txt /
RUN pip3 install -r requirements.txt
RUN pip3 install -r test_requirements.txt

COPY . /src/satosa
RUN pip3 install -e /src/satosa

WORKDIR /src/satosa

CMD ["/start.sh"]
